services:
 web:
   image: vulhub/magento:2.4.7-p1
   depends_on:
    - mysql
    - elasticsearch
   ports:
    - "8080:80"
   environment:
    - DB_HOST=mysql:3306
    - DB_NAME=magento
    - DB_USER=root
    - DB_PASSWORD=root
    - ADMIN_EMAIL=admin@vulhub.org
    - ADMIN_USER=admin
    - ADMIN_PASSWORD=vulhub123
    - ELASTICSEARCH_HOST=elasticsearch
    - ELASTICSEARCH_PORT=9200
 mysql:
   image: mysql:8.0
   environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=magento
 elasticsearch:
   image: elasticsearch:8.11.4
   environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    - ES_JAVA_OPTS=-Xms512m -Xmx512m
